# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEJNLoifMz2y7_tlhhvwKQmm1nNFka-h
"""

# ================================

# 🌿 STREAMLIT APP - HERBAL LEAF CLASSIFIER

# MobileNetV2 + GradCAM + Info Herbal

# ================================

import streamlit as st
import tensorflow as tf
import numpy as np
import pandas as pd
import cv2
from PIL import Image
import matplotlib.pyplot as plt

# ==================== CONFIG ====================

st.set_page_config(page_title="Klasifikasi Daun Herbal", page_icon="🌿", layout="wide")

IMG_SIZE = 224

CLASS_NAMES = [
"Belimbing Wuluh", "Jambu Biji", "Jeruk Nipis", "Kemangi",
"Lidah Buaya", "Nangka", "Pandan", "Pepaya", "Seledri", "Sirih"
]

# ==================== INFO HERBAL ====================

INFO_HERBAL = {
"Belimbing Wuluh": {
"manfaat": ["Batuk", "Hipertensi", "Jerawat", "Sariawan"],
"cara": ["Direbus dan diminum", "Ditumbuk lalu dioles"]
},
"Jambu Biji": {
"manfaat": ["Diare", "Trombosit", "Imunitas"],
"cara": ["Daun direbus", "Buah dijus"]
},
"Jeruk Nipis": {
"manfaat": ["Batuk", "Pencernaan", "Kulit"],
"cara": ["Peras + madu", "Air hangat"]
},
"Kemangi": {
"manfaat": ["Bau badan", "ASI", "Stres"],
"cara": ["Lalapan", "Diseduh"]
},
"Lidah Buaya": {
"manfaat": ["Luka bakar", "Rambut", "Pencernaan"],
"cara": ["Gel dioles", "Dibuat jus"]
},
"Nangka": {
"manfaat": ["Energi", "Pencernaan", "Imunitas"],
"cara": ["Dimakan segar", "Direbus"]
},
"Pandan": {
"manfaat": ["Rematik", "Hipertensi", "Insomnia"],
"cara": ["Direbus", "Diminum"]
},
"Pepaya": {
"manfaat": ["Pencernaan", "Kulit", "Antioksidan"],
"cara": ["Dimakan", "Masker"]
},
"Seledri": {
"manfaat": ["Tekanan darah", "Ginjal", "Diet"],
"cara": ["Jus", "Direbus"]
},
"Sirih": {
"manfaat": ["Antiseptik", "Bau mulut", "Mimisan"],
"cara": ["Direbus", "Dikunyah"]
}
}

# ==================== LOAD MODEL ====================

@st.cache_resource
def load_model_app():
    return tf.keras.models.load_model("daun-herbal.keras", compile=False)


model = load_model_app()

# ==================== FUNCTIONS ====================

def preprocess_image(image):
image = image.resize((IMG_SIZE, IMG_SIZE))
img = np.array(image)
img = tf.keras.applications.mobilenet_v2.preprocess_input(img)
img = np.expand_dims(img, axis=0)
return img

def make_gradcam(image, model, layer_name="out_relu"):
grad_model = tf.keras.models.Model(
[model.inputs],
[model.get_layer(layer_name).output, model.output]
)

```
with tf.GradientTape() as tape:
    conv_outputs, predictions = grad_model(image)
    pred_index = tf.argmax(predictions[0])
    loss = predictions[:, pred_index]

grads = tape.gradient(loss, conv_outputs)
pooled_grads = tf.reduce_mean(grads, axis=(0,1,2))
conv_outputs = conv_outputs[0]

heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
heatmap = tf.squeeze(heatmap)
heatmap = tf.maximum(heatmap, 0) / tf.reduce_max(heatmap)
return heatmap.numpy()
```

# ==================== UI ====================

st.title("🌿 Klasifikasi Daun Herbal Indonesia (MobileNetV2)")

uploaded_file = st.file_uploader("Upload gambar daun herbal", type=["jpg","png","jpeg"])

if uploaded_file:
image = Image.open(uploaded_file).convert("RGB")
st.image(image, caption="Gambar Asli", use_container_width=True)

```
img = preprocess_image(image)
preds = model.predict(img)
idx = np.argmax(preds)
label = CLASS_NAMES[idx]
conf = preds[0][idx] * 100

st.success(f"🎯 Prediksi: {label} ({conf:.2f}%)")

# ===== INFO HERBAL =====
st.subheader("🌱 Manfaat Herbal")
for m in INFO_HERBAL[label]["manfaat"]:
    st.markdown(f"- {m}")

st.subheader("🍵 Cara Penggunaan")
for c in INFO_HERBAL[label]["cara"]:
    st.markdown(f"- {c}")

# ===== PROBABILITAS =====
st.subheader("📊 Probabilitas Semua Kelas")
df = pd.DataFrame(preds[0], index=CLASS_NAMES, columns=["Probabilitas"])
st.bar_chart(df)

# ===== GRADCAM =====
heatmap = make_gradcam(img, model)

img_cv = cv2.cvtColor(np.array(image.resize((224,224))), cv2.COLOR_RGB2BGR)
heatmap = cv2.resize(heatmap, (224,224))
heatmap = np.uint8(255 * heatmap)
heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)
superimposed_img = cv2.addWeighted(img_cv, 0.6, heatmap, 0.4, 0)

st.subheader("🔥 Visualisasi Fokus Model (Grad-CAM)")
st.image(cv2.cvtColor(superimposed_img, cv2.COLOR_BGR2RGB), use_container_width=True)
```

else:
st.info("👆 Upload gambar daun herbal untuk memulai klasifikasi.")

st.markdown("---")
st.caption("Skripsi: Klasifikasi Daun Herbal Menggunakan MobileNetV2")
